server:
    port: 8080
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true
spring:
    config:
        import: application-dev.yml
    datasource:
        url: jdbc:mysql://localhost:3306/youfit
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    server:
        timezone: Asia/Seoul